apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.6.0
          imagePullPolicy: IfNotPresent
          command:
            - ./podinfo
            - --port=9898
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
          env:
            - name: PODINFO_UI_MESSAGE
              value: "GitOps Demo"
            - name: PODINFO_UI_COLOR
              value: "#34577c"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
