apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-staging
namePrefix: staging-

resources:
  - ../../base

# STAGING runs the candidate that has been promoted out of dev.
images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.7.0

replicas:
  - name: podinfo
    count: 2

patches:
  - target:
      kind: Deployment
      name: podinfo
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: podinfo
      spec:
        template:
          spec:
            containers:
              - name: podinfo
                env:
                  - name: PODINFO_UI_MESSAGE
                    value: "GitOps Demo - STAGING (v6.7.0)"
                  - name: PODINFO_UI_COLOR
                    value: "#d29922"
